/*
What is the 2s complement in C?
    The 2s complement in C is generated from the 1s complement in C. As we know that the 1s complement of a binary number is created by transforming bit 1 to 0 and 0 to 1; the 2s complement of a binary number is generated by adding one to the 1s complement of a binary number.

    In short, we can say that the 2s complement in C is defined as the sum of the one's complement in C and one.

    Example:
    the binary number is equal to 00010100, and its one's complement is calculated by transforming the bit 1 to 0 and 0 to 1 vice versa. Therefore, one's complement becomes 11101011. After calculating one's complement, we calculate the two's complement by adding 1 to the one's complement, and its result is 11101100.
*/



#include <stdio.h>  
int main()  
{  
   int n;  // variable declaration  
   printf("Enter the number of bits do you want to enter :");  
   scanf("%d",&n);  
   char binary[n+1];  // binary array declaration;   
   char onescomplement[n+1]; // onescomplement array declaration   
   char twoscomplement[n+1]; // twoscomplement array declaration  
   int carry=1; // variable initialization  
   printf("\nEnter the binary number : ");  
   scanf("%s", binary);  
   printf("%s", binary);  
   printf("\nThe ones complement of the binary number is :");  
     
   // Finding onescomplement in C  
   for(int i=0;i<n;i++)  
   {  
       if(binary[i]=='0')  
       onescomplement[i]='1';  
       else if(binary[i]=='1')  
       onescomplement[i]='0';  
   }  
   onescomplement[n]='\0';  
   printf("%s",onescomplement);  
    
  
printf("\nThe twos complement of a binary number is : ");  
  
// Finding twoscomplement in C  
for(int i=n-1; i>=0; i--)  
    {  
        if(onescomplement[i] == '1' && carry == 1)  
        {  
            twoscomplement[i] = '0';  
        }  
        else if(onescomplement[i] == '0' && carry == 1)  
        {  
            twoscomplement[i] = '1';  
            carry = 0;  
        }  
        else  
        {  
            twoscomplement[i] = onescomplement[i];  
        }  
    }  
twoscomplement[n]='\0';  
printf("%s",twoscomplement);  
return 0;  
}  




/*
Signed integers are frequently represented in C using the two's complement notation. Using the same binary representation offers a mechanism to express both positive and negative integers. The most significant bit (MSB) is used as the sign bit in a two's complement representation, where 0 denotes a positive integer, and 1 denotes a negative number.

Starting with a negative number's absolute value in binary form, you may take the one's complement (bitwise negation) of that value to get the two's complement representation of the negative integer. You add 1 to the resultant value to acquire the representation of the two's complement.

The two's complement encoding in C can represent signed integers and can perform fast arithmetic operations. One benefit of employing two's complement is the ability to do addition and subtraction using the same binary operations as for unsigned numbers.

The binary numbers are added together like unsigned integers when adding two's complement. A carry-out from the location of the main critical bit is just disregarded. Due to this fact, handling signed numbers differently is not necessary, and addition becomes simple.

Consider adding -5 and -3 using the 8-bit two's complement representation, for instance:

Binary number for -5 is 11111011.

Binary number for -3 is 11111101.

carrying out the addition:

11111011 (-5)  
11111101 (-3)  
-------------  
111110100 (-8)  
The answer is 111110100, which in two's complement is equal to -8.

Similar to addition, subtraction may be done by treating the second operand's two's complement as if it were addition. In other words, you add the two's complement of a negative number to the first operand to remove it.

For instance, when -3 is subtracted from -5:

In binary, -5 is represented by 11111011 and -(-3) by 00000011 (two's complement of -3)

Carrying out the subtraction

11111011 (-5)  
00000011 (+3)  
-------------  
11111110 (-8)  
The outcome is 11111110, which in two's complement is equal to -8.
*/